# Generated by Django 3.1.1 on 2020-10-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('orderrecieved:', 'orderrecieved'), ('dispatched', 'dispatched'), ('deliverd', 'deliverd')], default='orderrecieved', max_length=120),
        ),
    ]
