# Generated by Django 3.1.1 on 2020-10-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201005_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='noname', max_length=150),
            preserve_default=False,
        ),
    ]
